<?php
/*
 * This file is part of Laravel Pusher.
 *
 * (c) Vincent Klaiber <hello@vinkla.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

return [
    /*
    |--------------------------------------------------------------------------
    | Merchant Security Key
    |--------------------------------------------------------------------------
    |
    | The 32 byte security key generated by the bank.
    |
    */
    'merchant-key' => '12345678901234567890123456789012',

    /*
    |--------------------------------------------------------------------------
    | Merchant Identifier
    |--------------------------------------------------------------------------
    |
    | Unique merchant ID provided by the bank (3-4 characters).
    |
    */
    'merchant-id' => '123',

    /*
    |--------------------------------------------------------------------------
    | Phone number for SMS notifications
    |--------------------------------------------------------------------------
    |
    | Phone number where SMS notifications should be sent to. Use the full
    | international format, starting with '+', followed by the country code and
    | full number, e.g. '+1234567890123'. Maximum 15 characters.
    |
    */
    'notification-number' => '+1234567890123',

	/*
    |--------------------------------------------------------------------------
    | E-mail address for notifications
    |--------------------------------------------------------------------------
    |
    | E-mail address where the notifications should be sent to. Must be a valid
    | e-mail address according to RFC 2822, maximum 35 characters.
    |
    */
    'notification-email' => 'username@domain.com',
    
];
